name: Build/Release Staging Environment

on:
    push:
        branches:
            - staging

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: 18
            - name: install dependencies
              run: npm ci
            - name: publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run publish
